### ISSUE TITLE
Comments will not be displayed in the compiled css-file

### ISSUE THREAD

**Issue by janstieler** [bartvandebiezen/kirby-v2-lessphp#2]
Hi,
I installed actually now your version but I have the problem that Lessphp is not porting the comments from the less-file to the compiled css-file.
Normally Lessphp is support line-comments (//) and block-comments (/* */).
Have you an idea whats going wrong?
Is there an comment deleting function in your plugin?

Best wishes,
Jan

**Comment by bartvandebiezen** [comment]
Answer can be found via https://github.com/bartvandebiezen/kirby-v2-lessphp/issues/3
