### ISSUE TITLE
Plugin is compress the css-file althought it is set to false.

### ISSUE THREAD

**Issue by janstieler** [bartvandebiezen/kirby-v2-lessphp#3]
Hi,
the plugin compress the css-file althought I have set the config (snippet/less.php) to false.
It could be that this also solve my problem with the deleted comments.

Best wishes,
Jan

PS: Sorry for my closed issue. This was a double sending of my comment issue.
I tried to delete them but I was not possible.

**Comment by bartvandebiezen** [comment]
Hi @janstieler,
Yes, I added some extra compression to remove comments and other unused strings to make sure the file size would be even smaller without affecting the result. You can find them below line 35 in the snippet: https://github.com/bartvandebiezen/kirby-v2-lessphp/blob/master/snippets/less.php#L35
You can comment them out.
Gr. Bart
